networks:
  inception:
    driver: bridge

services:
  mariadb:
    image: mariadb:inception
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception

  wordpress:
    image: wordpress:inception
    build: ./requirements/wordpress
    container_name: wordpress
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception

  nginx:
    image: nginx:inception
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/sjoao/data/mariadb_data
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/sjoao/data/wordpress_data
      o: bind
