services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql


volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/sjoao/data/mariadb
      o: bind
